### ISSUE TITLE
Error with timeout in ie11

### ISSUE THREAD

**Issue by tume** [stephanebachelier/superapi#5]
I'm getting InvalidStateError with ie11 when doing requests and the "culprit" seems to be this line:
<code>
req.xhr.timeout = timeout;
</code>

If I remove it everything works fine. Not sure what is the actual cause because didn't have time to debug this more but my guess is that it is setting timeout too early/late and for some reason ie doesn't like it.

Superagent seems to provide some timeout support also so one option might be using that if possible?

One other related note is that would be nice to be able to skip the timeout by specifying 0 which is not really possible at the moment.

**Comment by stephanebachelier** [comment]
@tume I need to review this timeout logic. It was not tested correctly and it does not behave correctly. I'm thinking about rolling back. 
I know that superagent provide a support for timeout but it was not working as intended, or in other words not as I needed.

I'll come back soon with a better solution.

**Comment by krasimir** [comment]
Just for the record. The bug is gone (in IE11) if you set the timeout after the `open` method. So if you have
```js
this.xhr.timeout = 5000;
xhr.open("GET", 'http://....', true);
```
you'll get the exception. The following works fine:
```js
xhr.open("GET", 'http://....', true);
this.xhr.timeout = 5000;
```
I guess the **lovely** IE11 wants to have the XHR object initialized before getting more *commands*.

cc @stephanebachelier @tume
